import { CircularProgressbar } from "react-circular-progressbar";
import "react-circular-progressbar/dist/styles.css";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import {
  FileBarChart2,
  CheckCircle,
  AlertCircle,
  Lightbulb,
  Download,
} from "lucide-react";

export default function Analysis() {
  const analysis =
    JSON.parse(
      localStorage.getItem("analysis")
    ) || {};

  const atsScore =
    analysis.atsScore || 0;

  const matchedSkills =
    analysis.matchedSkills || [];

  const missingSkills =
    analysis.missingSkills || [];

  const suggestions =
    analysis.suggestions || [];

  const downloadPDF = () => {
    const doc = new jsPDF();

    const user =
      JSON.parse(
        localStorage.getItem("user")
      ) || {};

    // Header
    doc.setFillColor(37, 99, 235);
    doc.rect(0, 0, 210, 35, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text(
      "AI Resume Analyzer",
      15,
      18
    );

    doc.setFontSize(11);
    doc.text(
      "Professional ATS Analysis Report",
      15,
      27
    );

    // User Information
    doc.setTextColor(0, 0, 0);

    doc.setFontSize(12);

    doc.text(
      `Candidate: ${user.name || "User"
      }`,
      15,
      50
    );

    doc.text(
      `Email: ${user.email || "N/A"
      }`,
      15,
      58
    );

    doc.text(
      `Generated: ${new Date().toLocaleDateString()}`,
      15,
      66
    );

    // ATS Score Card
    doc.setDrawColor(220);

    doc.roundedRect(
      15,
      75,
      180,
      30,
      4,
      4
    );

    doc.setFontSize(14);

    doc.text(
      "ATS SCORE",
      25,
      92
    );

    doc.setTextColor(
      37,
      99,
      235
    );

    doc.setFontSize(26);

    doc.text(
      `${atsScore}%`,
      145,
      92
    );

    doc.setTextColor(0, 0, 0);

    // Matched Skills Table
    autoTable(doc, {
      startY: 120,
      head: [["Matched Skills"]],
      body:
        matchedSkills.length > 0
          ? matchedSkills.map(
            (skill) => [skill]
          )
          : [["No matched skills"]],
      headStyles: {
        fillColor: [34, 197, 94],
      },
    });

    // Missing Skills Table
    autoTable(doc, {
      startY:
        doc.lastAutoTable.finalY +
        10,
      head: [["Missing Skills"]],
      body:
        missingSkills.length > 0
          ? missingSkills.map(
            (skill) => [skill]
          )
          : [["No missing skills"]],
      headStyles: {
        fillColor: [239, 68, 68],
      },
    });

    // Suggestions Table
    autoTable(doc, {
      startY:
        doc.lastAutoTable.finalY +
        10,
      head: [["AI Suggestions"]],
      body:
        suggestions.length > 0
          ? suggestions.map(
            (item) => [item]
          )
          : [["No suggestions"]],
      headStyles: {
        fillColor: [59, 130, 246],
      },
    });

    // Footer
    const pageHeight =
      doc.internal.pageSize.height;

    doc.line(
      15,
      pageHeight - 15,
      195,
      pageHeight - 15
    );

    doc.setFontSize(10);

    doc.text(
      "Generated by AI Resume Analyzer",
      15,
      pageHeight - 8
    );

    doc.save(
      `${user.name || "Resume"
      }_ATS_Report.pdf`
    );
  };
  return (
    <div>
      {/* Header */}
      <div className="mb-8 flex justify-between items-center">
        <div>
          <div className="flex items-center gap-3">
            <FileBarChart2
              size={36}
              className="text-blue-600"
            />

            <h1 className="text-4xl font-bold">
              Resume Analysis
            </h1>
          </div>

          <p className="text-slate-500 mt-2">
            AI-generated ATS report
          </p>
        </div>

        <button
          onClick={downloadPDF}
          className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-5 py-3 rounded-xl transition"
        >
          <Download size={18} />
          Download PDF
        </button>
      </div>

      {/* Top Section */}
      <div className="grid lg:grid-cols-2 gap-6 mb-8">
        {/* ATS Score */}
        <div className="bg-white rounded-3xl shadow-md p-8">
          <h2 className="text-2xl font-semibold mb-6">
            ATS Score
          </h2>

          <div className="w-52 mx-auto">
            <CircularProgressbar
              value={atsScore}
              text={`${atsScore}%`}
            />
          </div>

          <p className="text-center mt-4 text-slate-500">
            Resume ATS Compatibility
            Score
          </p>
        </div>

        {/* Summary */}
        <div className="bg-white rounded-3xl shadow-md p-8">
          <h2 className="text-2xl font-semibold mb-6">
            Analysis Summary
          </h2>

          <div className="space-y-5">
            <div className="flex justify-between items-center bg-green-50 p-4 rounded-xl">
              <span className="font-medium">
                Matched Skills
              </span>

              <span className="font-bold text-green-600">
                {
                  matchedSkills.length
                }
              </span>
            </div>

            <div className="flex justify-between items-center bg-red-50 p-4 rounded-xl">
              <span className="font-medium">
                Missing Skills
              </span>

              <span className="font-bold text-red-600">
                {
                  missingSkills.length
                }
              </span>
            </div>

            <div className="flex justify-between items-center bg-blue-50 p-4 rounded-xl">
              <span className="font-medium">
                Suggestions
              </span>

              <span className="font-bold text-blue-600">
                {
                  suggestions.length
                }
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* Matched Skills */}
      <div className="bg-white rounded-3xl shadow-md p-8 mb-8">
        <div className="flex items-center gap-3 mb-6">
          <CheckCircle className="text-green-600" />

          <h2 className="text-2xl font-semibold">
            Matched Skills
          </h2>
        </div>

        <div className="flex flex-wrap gap-3">
          {matchedSkills.length >
            0 ? (
            matchedSkills.map(
              (skill) => (
                <span
                  key={skill}
                  className="bg-green-100 text-green-700 px-4 py-2 rounded-full"
                >
                  {skill}
                </span>
              )
            )
          ) : (
            <p className="text-slate-500">
              No matched skills
              found.
            </p>
          )}
        </div>
      </div>

      {/* Missing Skills */}
      <div className="bg-white rounded-3xl shadow-md p-8 mb-8">
        <div className="flex items-center gap-3 mb-6">
          <AlertCircle className="text-red-600" />

          <h2 className="text-2xl font-semibold">
            Missing Skills
          </h2>
        </div>

        <div className="flex flex-wrap gap-3">
          {missingSkills.length >
            0 ? (
            missingSkills.map(
              (skill) => (
                <span
                  key={skill}
                  className="bg-red-100 text-red-700 px-4 py-2 rounded-full"
                >
                  {skill}
                </span>
              )
            )
          ) : (
            <p className="text-slate-500">
              No missing skills
              detected.
            </p>
          )}
        </div>
      </div>

      {/* Suggestions */}
      <div className="bg-white rounded-3xl shadow-md p-8">
        <div className="flex items-center gap-3 mb-6">
          <Lightbulb className="text-yellow-500" />

          <h2 className="text-2xl font-semibold">
            ATS Suggestions
          </h2>
        </div>

        <div className="grid md:grid-cols-2 gap-4">
          {suggestions.length >
            0 ? (
            suggestions.map(
              (item, index) => (
                <div
                  key={index}
                  className="bg-slate-50 border rounded-2xl p-4"
                >
                  • {item}
                </div>
              )
            )
          ) : (
            <p className="text-slate-500">
              No suggestions
              available.
            </p>
          )}
        </div>
      </div>
    </div>
  );
}